# docker-compose.yml
version: '3.8'

services:
  bannerly:
    # MODIFIED: This now pulls your image from Docker Hub.
    # Replace 'your-dockerhub-username' with your actual Docker Hub username.
    image: plumpninja/bannerly:latest
    container_name: bannerly
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # This volume for persistent data remains the same and is essential.
      - ./bannerly-data:/app/data
